name: meilisearch
description: MeiliSearch SDK for dart language.
version: 0.1.0
homepage: https://github.com/themisir/meilisearch-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10

dev_dependencies:
  test: ^1.15.7
