name: Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["2.7", "2.8"]
    container:
      image:  google/dart:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v1
      - name: Docker setup
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key=masterKey
      - name: Install dependencies
        run: |
          cd ./meilisearch
          pub get
      - name: Run tests
        run: pub run test